stef_dag_van_de_week_calendar_show:
    pattern:  /kalender/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:Calendar:show }
    requirements:
        _method:  GET

stef_dag_van_de_week_calendar_index:
    pattern:  /kalender
    defaults: { _controller: StefDagVanDeWeekBundle:Calendar:showIndex }
    requirements:
        _method:  GET