stef_dag_van_de_week_history_article_show:
    pattern:  /historie/{year}/{month}/{day}/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showArticle }
    requirements:
        _method:  GET

stef_dag_van_de_week_history_year_month_day_show:
    pattern:  /historie/{year}/{month}/{day}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYearMonthDay }
    requirements:
        _method:  GET

stef_dag_van_de_week_history_year_month_show:
    pattern:  /historie/{year}/{month}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYearMonth }
    requirements:
        _method:  GET

stef_dag_van_de_week_history_year_show:
    pattern:  /historie/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYear }
    requirements:
        _method:  GET

stef_dag_van_de_week_history_index:
    pattern:  /historie
    defaults: { _controller: StefDagVanDeWeekBundle:History:showIndex }
    requirements:
        _method:  GET